### ISSUE TITLE
[Bug] Multiblock Tweaker used with GTCE 1.15 causes JEI to fail at loading machine recipes and multiblock patterns

### ISSUE THREAD

**Issue by BraggestSage833** [eutropius225/MultiblockTweaker#14]
Mod used:
GTCE1.15
JEI 4.1.20.586
Multiblock Tweaker 1.3.2 

New world created: yes

Issue: As mentioned on discord GTCE 1.15 introduced [#1580](https://github.com/GregTechCE/GregTech/pull/1580). If Multiblock Tweaker is used to make a recipe map (and/or) multiblock pattern with GTCE 1.15, no multiblock patterns show up in jei other than Multiblock Tweaker's. This also causes all machines to lose their jei recipe map pages. I have included an image of the JEI multiblock pattern screen and the [script used](https://github.com/BraggestSage833/tempForMBT/blob/main/CokeOven.zs)
![2021-05-20_12 29 19](https://user-images.githubusercontent.com/46819052/119015659-1c26b180-b967-11eb-893c-f4354840bf98.png)

**Comment by Exaxxion** [comment]
@ALongStringOfNumbers and I are looking into this and it seems that while most of the property methods were deprecated and routed to the new implementation automatically, the property key set accessor method was not one of them. Since the method it's trying to call no longer exists, the mod is breaking at runtime.

It should be pretty simple to patch this by fixing the few places where now-nonexistent methods are called, but in the longer term the deprecated functions should also be replaced with the new Recipe Property storage methods.

**Comment by serenibyss** [comment]
I can confirm that the fix suggested will work, that is all it took for me to do similarly in Gregicality
