### ISSUE TITLE
Internal Exception handling: Should go to CT logs

### ISSUE THREAD

**Issue by pyure** [eutropius225/MultiblockTweaker#6]
Eutro, mostly a reminder: I ran into a small issue where I was using an incorrect number of expected vs actual inputs, and the exception was thrown to the minecraft standard logs.  It would be nice if these were caught and thrown to the CT logs.

**Comment by eutro** [comment]
Thanks! If you could attach the relevant log and scripts that would be incredibly helpful.

**Comment by eutro** [comment]
Having replicated it [as such](https://gist.github.com/eutropius225/8d59461a53fa7b6e39b8722ec106a41f), it seems the problem is on [GregTech itself](https://gist.github.com/eutropius225/8d59461a53fa7b6e39b8722ec106a41f#file-latest-log-L129-L133), as it logs recipe errors [directly to the logger](https://github.com/GregTechCE/GregTech/blob/032ca8f0bc8d0107bc9a544257a7f8b83b0c7cd9/src/main/java/gregtech/api/recipes/RecipeMap.java#L181-L199).

**Comment by eutro** [comment]
I opened https://github.com/GregTechCE/GregTech/issues/1119.
